# Name of workflow
name: Development workflow

# When workflow is triggered
on:
  push:
    branches:
      - main

# Jobs to carry out
jobs:
  deploy:
    name: Node.js ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        node: [16]
        os: [ubuntu-latest]

    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v2

      - name: Setup node env 🔧
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies 🧹
        run: npm ci

      - name: build your code
        run: npm run build --if-present

      # Deploy to Netlify using our dev secrets
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["DEV_NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
